export const ICON_SIZE_MAP = {
  small: '16px',
  medium: '20px',
  large: '24px',
} as const;

export const ICON_NAMES = [
  'arrow_down',
  'arrow_left',
  'arrow_right',
  'arrow_up',
  'cancel',
  'close',
  'direction_down',
  'direction_left',
  'direction_right',
  'direction_up',
  'download',
  'edit',
  'drop_down_arrow',
  'dummy',
  'help',
  'home_artwork',
  'home',
  'iconoir_book',
  'instagram_color',
  'instagram_gray',
  'link',
  'magazine',
  'plus',
  'settings',
  'share',
  'upload',
] as const;
