import '@/styles/global.css';

import { css } from '@/styled-system/css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={css({ bg: 'grayscale.900' })}>{children}</body>
    </html>
  );
}
